run:
  concurrency: 4
  timeout: 5m
  skip-dirs-use-default: true

issues:
  new: true

linters:
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - gci
    - gocritic
    - gofmt
    - gofumpt
    - goimports
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nilerr
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - unparam
    - whitespace
  disable:
    - errcheck