PORT: 42069
MASTER_VERSION: 7130000
PACK_VERSION: 6120000
IS_MAINTENANCE_MODE: false
MAIN_DOMAIN: "msattack.snkplaymore.info"
STORAGE_DOMAIN: "strage.snkplaymore.info"
DATA_STORAGE_ENDPOINT: "/snkp/msatk/prod"