on:
  push:
    branches:
      - main
  pull_request:
name: Security
jobs:
  gosec:
    name: Golang Security Checker
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v3
      - name: Run Gosec
        uses: securego/gosec@master
        with:
          args: -exclude-dir=vendor/*/ ./...